name: Deploy Docker Image Locally

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Pull Docker Image
      run: docker pull monikashanthakumar/github-actions-docker-java-app:0.0.1.Release

    - name: Run Docker Container
      run: docker run -p 5000:5000 monikashanthakumar/github-actions-docker-java-app:0.0.1.Release
